obstacle_avoidance_node:
  ros__parameters:

    stop_dist:       0.35
    clear_dist:      0.55
    reverse_dist:    0.20

    fwd_speed:       0.25
    turn_speed:      0.80
    strafe_speed:    0.20

    turn_duration:    1.20
    reverse_duration: 0.80

    max_distance: 1.0
    warn_distance: 0.5


bug2_node:
  ros__parameters:
    stop_dist:       0.35
    wall_dist:       0.30
    wall_tol:        0.05
    clear_dist:      0.50
    goal_radius:     0.15
    mline_tol:       0.08

    fwd_speed:       0.20
    turn_speed:      0.60
    wall_fwd_speed:  0.15
    wall_kp:         1.20
    heading_kp:      1.00