obstacle_avoidance_node:
  ros__parameters:
    stop_dist:          0.55
    clear_dist:         1.00
    reverse_dist:       0.20
    fwd_speed:          0.25
    turn_speed:         0.80
    reverse_duration:   0.80
    robot_diameter:     0.80
 
    kp:                 0.80
    ki:                 0.15
    ki_max:             0.30
 
    wall_lost_dist:     0.5
    wall_corridor_dist: 0.25

    sensor_timeout:     0.5


joy_vel:
  ros__parameters:
    linear_speed:   0.3
    angular_speed:  0.8
    deadman_button: 6
    axis_linear_x:  1
    axis_linear_y:  0
    axis_angular_z: 2
    stop_dist:       0.40
    safety_kp:       1.1
    safety_ki:       0.8


bug2_node:
  ros__parameters:
    stop_dist:        0.35
    goal_radius:      0.15
    fwd_speed:        0.20
    heading_kp:       1.0
    scan_settle_time: 0.30
    wall_fwd_speed:   0.15
    wall_kp:          0.80
    min_drive_dist:   0.50
    clear_dist:       0.80
    perp_tol:         0.05
    strafe_speed:     0.15